name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Cliente1
      - APELLIDO=Apellido1
      - DOCUMENTO=30000001
      - NACIMIENTO=1990-02-02
      - NUMERO=1001
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/.data/agency-1.csv
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
