name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Cliente1
      - APELLIDO=Apellido1
      - DOCUMENTO=30000001
      - NACIMIENTO=1990-02-02
      - NUMERO=1001
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NOMBRE=Cliente2
      - APELLIDO=Apellido2
      - DOCUMENTO=30000002
      - NACIMIENTO=1990-03-03
      - NUMERO=1002
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - NOMBRE=Cliente3
      - APELLIDO=Apellido3
      - DOCUMENTO=30000003
      - NACIMIENTO=1990-04-04
      - NUMERO=1003
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - NOMBRE=Cliente4
      - APELLIDO=Apellido4
      - DOCUMENTO=30000004
      - NACIMIENTO=1990-05-05
      - NUMERO=1004
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - NOMBRE=Cliente5
      - APELLIDO=Apellido5
      - DOCUMENTO=30000005
      - NACIMIENTO=1990-06-06
      - NUMERO=1005
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
